from __future__ import annotations

from enum import Enum
from typing import TypedDict

INFINITY_DISTANCE: int

class Symmetry(Enum):
    IDENTITY = 0
    ROTATE_90 = 1
    ROTATE_180 = 2
    ROTATE_270 = 3
    FLIP_HORIZONTAL = 4
    FLIP_VERTICAL = 5
    DIAGONAL_MAIN = 6
    DIAGONAL_ANTI = 7

class ShortestEscape(TypedDict):
    distance: int
    first_steps: list[str]

class UndoToken: ...

class State:
    def __init__(self, size: int = 17) -> None: ...
    @property
    def size(self) -> int: ...
    @property
    def ply(self) -> int: ...
    @property
    def ball(self) -> tuple[int, int]: ...
    @property
    def turn(self) -> str: ...
    @property
    def posts(self) -> list[str | None]: ...
    @property
    def outcome(self) -> dict[str, str | None]: ...
    def post(self, row: int, col: int) -> str | None: ...
    def set_post(self, row: int, col: int, value: str | None) -> None: ...
    def set_ball(self, row: int, col: int) -> None: ...
    def set_turn(self, player: str) -> None: ...
    def is_anchored(self, row: int, col: int) -> bool: ...
    def legal_move_kind(self, action: int) -> str | None: ...
    def legal_actions(self) -> list[int]: ...
    def walls(self) -> list[tuple[str, int, int, str]]: ...
    def first_step_costs(self) -> list[int]: ...
    def directional_exit_distances(self) -> list[int]: ...
    def shortest_escape(self) -> ShortestEscape: ...
    def apply(self, action: int) -> State: ...
    def apply_in_place(self, action: int) -> UndoToken: ...
    def undo(self, token: UndoToken) -> None: ...
    def adjudicate_turn_start(self) -> None: ...
    def hash(self) -> int: ...
    def serialize(self) -> bytes: ...
    @staticmethod
    def deserialize(data: bytes) -> State: ...
    def transformed(self, symmetry: Symmetry) -> State: ...

def transform_action(action: int, size: int, symmetry: Symmetry) -> int: ...
